#\u7AEF\u53E3\u53F7
server:
  port: 8002
#\u5E94\u7528\u540D
spring:
  application:
    name: consumer-feign
  #\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  #\u6CE8\u518C\u670D\u52A1\u7684\u65F6\u5019\u6307\u5B9A\u4F7F\u7528ip\u5730\u5740\u8FDB\u884C\u6CE8\u518C
  instance:
    prefer-ip-address: true


