#server.port=7001
server:
  port: 7001
##\u670D\u52A1\u63D0\u4F9B\u8005\u53D6\u540D
#spring.application.name=server-01
spring:
  application:
    name: provider-01
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    # 这里需要配置
    fetch-registry: false

  instance:
    prefer-ip-address: true



