server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway9527


  cloud:
    gateway:
      routes:
        #配置写法问题，需要看看原文档
        - id: swift
          uri: lb://provider-01
          predicates:
#          - After=2021-01-20T17:42:47.789-07:00[America/Denver]
            - Path=/get/user/**


eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
    register-with-eureka: true
    fetch-registry: true


