## \u5E94\u7528\u540D\u79F0
#spring.application.name=microservicecloud-config-3355
## \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
#server.port=8080
## Actuator Web \u8BBF\u95EE\u7AEF\u53E3
#management.server.port=8081
#management.endpoints.jmx.exposure.include=*
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

#spring:
##application:
#name: cloud-stream-provider
spring:
  application:
    name: microservicecloud-config-3355
#      stream:
  #\u914D\u7F6E\u6587\u4EF6\u540D
  cloud:
    config:
      name: microservicecloud-config-client
      #\u5206\u503C\u540D\u79F0
      label: master
      #\u8BFB\u53D6\u7684\u540E\u7F00\u540D
      profile: test
      \u914D\u7F6E\u4E2D\u5FC3\u5730\u5740
      uri: http://loucahost:3344
server:
  port: 3366
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#\u66B4\u9732\u76D1\u63A7\u7AEF\u70B9
management:
  endpoints:
    web:
      exposure:
        include: "*"