#server.port=7001
server:
 port: 7004
##\u670D\u52A1\u63D0\u4F9B\u8005\u53D6\u540D
#spring.application.name=server-01
spring:
 application:
  name: provider-hystrix-7004
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
# \u8FD9\u91CC\u9700\u8981\u914D\u7F6E
  fetch-registry: false

 instance:
  prefer-ip-address: true



