#端口号
server:
  port: 8001
##\u670D\u52A1\u63D0\u4F9B\u8005\u53D6\u540D
#服务提供者取名
spring:
  application:
    name: consumer-01
eureka:
  #指定注册中心的地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  #注册服务的时候指定使用ip地址进行注册
  instance:
    prefer-ip-address: true




