#\u5E94\u7528\u540D\u79F0
spring:
  application:
    name: spring-eureka-8763
##\u914D\u7F6Eeureka\u7684\u7AEF\u53E3\u53F7
server:
  port: 8763
##eureka\u76F8\u5173\u914D\u7F6E
eureka:
  instance:
    hostname: eureka-server
  ##\u4E0D\u5E0C\u671B\u81EA\u5DF1\u4E5F\u6CE8\u518C\u5230eureka\u4E2D
  client:
    register-with-eureka: false
    ##\u4E0D\u4ECEeureka\u4E2D\u83B7\u53D6\u5230\u6CE8\u518C\u4FE1\u606F
    fetch-registry: false
    ##\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


